libs = [
    "Box2D",
    "PocoFoundation",
    "sfml-graphics",
    "sfml-window",
    "sfml-system",
]

flags = [
    "-std=c++11",
    "-Wall",
    "-O3",
]

source_dir = "src/"

files = [
    "application.cc",
    "bounding_box.cc",
    "button.cc",
    "file_list.cc",
    "graph.cc",
    "main.cc",
    "utility.cc",
    "vertex.cc",
    "world.cc",
]

env = Environment(CXX="clang++")

env.Program(
    target="diploma",
    source=list(map(lambda s: "src/" + s, files)),
    CXXFLAGS=flags,
    LIBS=libs,
)
