"""empty message

Revision ID: 226bbc3296c
Revises: 1ba1aa4886b
Create Date: 2016-01-18 21:52:03.565811

"""

# revision identifiers, used by Alembic.
revision = '226bbc3296c'
down_revision = '1ba1aa4886b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
