"""empty message

Revision ID: 38ab5a684ce
Revises: 52d06063d2d
Create Date: 2016-01-17 20:30:49.586240

"""

# revision identifiers, used by Alembic.
revision = '38ab5a684ce'
down_revision = '52d06063d2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
