"""empty message

Revision ID: 3d873e20b7b
Revises: 47860598a11
Create Date: 2016-01-17 20:41:43.551250

"""

# revision identifiers, used by Alembic.
revision = '3d873e20b7b'
down_revision = '47860598a11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
