"""empty message

Revision ID: 47860598a11
Revises: 38ab5a684ce
Create Date: 2016-01-17 20:37:22.324930

"""

# revision identifiers, used by Alembic.
revision = '47860598a11'
down_revision = '38ab5a684ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
