"""empty message

Revision ID: 4ea1387d765
Revises: 512836e62f1
Create Date: 2016-01-20 13:28:13.579920

"""

# revision identifiers, used by Alembic.
revision = '4ea1387d765'
down_revision = '512836e62f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
