
env = Environment(CXX="clang++")
flags = ["-std=c++14"]

env.Program(
    target="a.sol",
    source="solution_a.cc",
    CXXFLAGS=flags
)

env.Program(
    target="b.sol",
    source="solution_b.cc",
    CXXFLAGS=flags
)

env.Program(
    target="c.sol",
    source="solution_c.cc",
    CXXFLAGS=flags
)

env.Program(
    target="d.sol",
    source="solution_d.cc",
    CXXFLAGS=flags
)

env.Program(
    target="e.sol",
    source="solution_e.cc",
    CXXFLAGS=flags
)

env.Program(
    target="f.sol",
    source="solution_f.cc",
    CXXFLAGS=flags
)