
libs = [
    "-lBox2D",
    "-lsfml-graphics",
    "-lsfml-window",
    "-lsfml-system",
]

flags = [
    "-std=c++11",
    "-Wall",
    "-O3",
]

sources = "main.cc"

env = Environment(
    CXX = "clang++",
)

env.Program( target="sfml-box2d", source=sources, CXXFLAGS=flags, LIBS=libs )
