# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Thu Aug 27 14:11:38 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 399)
        self.gridLayout = QtGui.QGridLayout(MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.player_names_layout = QtGui.QVBoxLayout()
        self.player_names_layout.setObjectName("player_names_layout")
        self.players_lst = QtGui.QListWidget(MainWindow)
        self.players_lst.setMinimumSize(QtCore.QSize(400, 0))
        self.players_lst.setObjectName("players_lst")
        self.player_names_layout.addWidget(self.players_lst)
        self.verticalLayout_2.addLayout(self.player_names_layout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.create_player_btn = QtGui.QPushButton(MainWindow)
        self.create_player_btn.setObjectName("create_player_btn")
        self.verticalLayout.addWidget(self.create_player_btn)
        self.show_modal_btn = QtGui.QPushButton(MainWindow)
        self.show_modal_btn.setObjectName("show_modal_btn")
        self.verticalLayout.addWidget(self.show_modal_btn)
        self.play_match_btn = QtGui.QPushButton(MainWindow)
        self.play_match_btn.setObjectName("play_match_btn")
        self.verticalLayout.addWidget(self.play_match_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtGui.QLabel(MainWindow)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.lobby_lst = QtGui.QListWidget(MainWindow)
        self.lobby_lst.setMaximumSize(QtCore.QSize(16777215, 75))
        self.lobby_lst.setObjectName("lobby_lst")
        self.verticalLayout_3.addWidget(self.lobby_lst)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(MainWindow)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(MainWindow)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(MainWindow)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(MainWindow)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.pts_to_win_game_lbl = QtGui.QLabel(MainWindow)
        self.pts_to_win_game_lbl.setObjectName("pts_to_win_game_lbl")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.pts_to_win_game_lbl)
        self.pts_to_win_tiebreak_lbl = QtGui.QLabel(MainWindow)
        self.pts_to_win_tiebreak_lbl.setObjectName("pts_to_win_tiebreak_lbl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.pts_to_win_tiebreak_lbl)
        self.sets_to_win_match_lbl = QtGui.QLabel(MainWindow)
        self.sets_to_win_match_lbl.setObjectName("sets_to_win_match_lbl")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.sets_to_win_match_lbl)
        self.label_9 = QtGui.QLabel(MainWindow)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(MainWindow)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_10)
        self.final_set_tiebreak_lbl = QtGui.QLabel(MainWindow)
        self.final_set_tiebreak_lbl.setObjectName("final_set_tiebreak_lbl")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.final_set_tiebreak_lbl)
        self.tiebreaks_lbl = QtGui.QLabel(MainWindow)
        self.tiebreaks_lbl.setObjectName("tiebreaks_lbl")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.tiebreaks_lbl)
        self.games_to_win_set_lbl = QtGui.QLabel(MainWindow)
        self.games_to_win_set_lbl.setObjectName("games_to_win_set_lbl")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.games_to_win_set_lbl)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.create_player_btn.setText(QtGui.QApplication.translate("MainWindow", "Create New Player", None, QtGui.QApplication.UnicodeUTF8))
        self.show_modal_btn.setText(QtGui.QApplication.translate("MainWindow", "Configure Match", None, QtGui.QApplication.UnicodeUTF8))
        self.play_match_btn.setText(QtGui.QApplication.translate("MainWindow", "Play Match", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Match Lobby", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Points to win game", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Points to win tiebreak", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Games to win set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sets to win match", None, QtGui.QApplication.UnicodeUTF8))
        self.pts_to_win_game_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pts_to_win_tiebreak_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.sets_to_win_match_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Tiebreaks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Final set tiebreak", None, QtGui.QApplication.UnicodeUTF8))
        self.final_set_tiebreak_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tiebreaks_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.games_to_win_set_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

