
flags = [
    "-Wall",
    "-O3",
    "-std=c++11"
]

common_sources = [
    src_dir + "main.cc",
    src_dir + "mage.cc",
    src_dir + "society.cc",
]

test_lib = ["cppunit"]

src_dir  = "src/"
test_dir = "test/"

env = Environment( CXX="clang++" )
env.Append( CPPPATH="." )

common_objects = env.Object( source=common_sources, CXXFLAGS=flags )

env.Program(
    target="mg",
    source=main_source+common_objects,
)
