
flags = [
    "-std=c++11",
    "-Wall"
]

libs = [
    "-lsfml-graphics",
    "-lsfml-window", 
    "-lsfml-system",
]

folder = "Sources/"

sources = [
    folder + "Aircraft.cpp",
    folder + "Application.cpp",
    folder + "Button.cpp",
    folder + "Command.cpp",
    folder + "CommandQueue.cpp",
    folder + "Component.cpp",
    folder + "Container.cpp",
    folder + "DataTables.cpp",
    folder + "Entity.cpp",
    folder + "GameOverState.cpp",
    folder + "GameState.cpp",
    folder + "Label.cpp",
    folder + "LoadingState.cpp",
    folder + "MenuState.cpp",
    folder + "ParallelTask.cpp",
    folder + "PauseState.cpp",
    folder + "Pickup.cpp",
    folder + "Player.cpp",
    folder + "Projectile.cpp",
    folder + "SceneNode.cpp",
    folder + "SettingsState.cpp",
    folder + "SpriteNode.cpp",
    folder + "State.cpp",
    folder + "StateStack.cpp",
    folder + "TextNode.cpp",
    folder + "TitleState.cpp",
    folder + "Utility.cpp",
    folder + "World.cpp",
    folder + "Main.cpp",
]

Program( target="airstrike-sfml-0.7", source=sources, LIBS=libs, CXXFLAGS=flags )
