
flags = [
    "-std=c++11",
    "-Wall",
    "-O3",
    "pkg-config --cflags eigen3",
]

sources = [
    "main.cc",
]

env = Environment( CXX="clang++" )

env.Program(
    target="lp-lw3",
    source=sources,
    CXXFLAGS=flags,
)
